Upgrade ruby, rails, gems, fix quality issues, refactor some parts

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,35 +1,37 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'fileutils'
+include FileUtils
 
-set -e
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-# Setup specific Bundler options if this is CI
-if [ "$CI" ]; then
-  BUNDLER_ARGS="--without development staging production"
-fi
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Make sure we have Bundler installed
-gem install bundler --conservative
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-# Set up Ruby dependencies via Bundler into .bundle folder
-rm -f .bundle/config
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check --path .bundle > /dev/null 2>&1') || system!('bundle install --path=.bundle')
 
-bundle check --path .bundle > /dev/null 2>&1 ||
-  bundle install --path=.bundle $BUNDLER_ARGS
+  puts "\n== Copying sample files =="
+  unless File.exist?('config/database.yml')
+    cp 'config/database.yml.sample', 'config/database.yml'
+  end
 
-# Set up configurable environment variables
-if [ ! -f .env ]; then
-  cp .env.example .env
-fi
+  unless File.exist?('.env')
+    cp '.env.sample', '.env'
+  end
 
-if [ ! -f config/database.yml ]; then
-  cp config/database.yml.example config/database.yml
-fi
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
 
-# Set up database and add any development seed data
-bundle exec rake db:setup
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
 
-# Removing old logs and tempfiles
-bin/rails log:clear tmp:clear
-
-# Restarting application server
-bin/rails restart
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
